plugins {
    id 'java'
    id 'net.fabricmc.fabric-loom'
}

base {
    archivesName = "${rootProject.mod_name}-Fabric-${minecraft_version}"
}

var commonAW = project(":common").file("src/main/resources/ecologics.accesswidener")
var generatedResources = file("src/generated/resources")

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
	api include("me.shedaniel.cloth:cloth-config-fabric:${rootProject.cloth_fabric_version}") {
        exclude(group: "net.fabricmc.fabric-api")
    }
    implementation "com.terraformersmc:modmenu:${project.modmenu_version}", {
        exclude module: "fabric-api"
    }
    implementation project(":common")
}
repositories {
    maven { url "https://maven.shedaniel.me/" }
    maven { url "https://maven.terraformersmc.com/releases" }
	maven { url "https://cursemaven.com" } 
}

tasks.withType(AbstractTestTask).configureEach {
    failOnNoDiscoveredTests = false
}

sourceSets {
    main {
        resources {
            srcDir generatedResources
        }
    }
}

task copyAW(type: Copy) {
    from commonAW
    into generatedResources
}

tasks.withType(JavaCompile).configureEach {
    source(project(":common").sourceSets.main.allSource)
}
tasks.withType(Javadoc).configureEach {
    source(project(":common").sourceSets.main.allJava)
}

processResources {
    // dependsOn copyAW
    from project(":common").sourceSets.main.resources
    inputs.property "version", rootProject.version

    filesMatching("fabric.mod.json") {
        expand "version": rootProject.version
    }
}