# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=2.4.1
group=samebutdifferent
java_version=21

# Parchment
parchment_minecraft=1.21.10
parchment_version=2025.10.12

# Common
minecraft_version=1.21.11
mod_name=Ecologics
mod_author=SameButDifferent
mod_id=ecologics
license=CC0-1.0
credits=SameButDifferent, Zero_DSRS_VX, Drigonis, Crispytwig, Irishjevil, Foquito Azul, Kitteh6660
description=Mod that alters some biomes in a neat and vanilla way!
minecraft_version_range=[1.21.11, 1.22)
neo_form_version=1.21.11-20251209.172050

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_version=0.139.5+1.21.11
fabric_loader_version=0.18.2
cloth_fabric_version=21.11.153
modmenu_version=17.0.0-beta.2

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=21.11.3-beta
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
