## Ecologics Build Properties

# Project
version=2.6.0
group=samebutdifferent
java_version=25

# Common
minecraft_version=26.2
mod_name=Ecologics
mod_author=SameButDifferent
mod_id=ecologics
license=CC0-1.0
credits=SameButDifferent, Zero_DSRS_VX, Drigonis, Crispytwig, Irishjevil, Foquito Azul, Kitteh6660
description=Mod that alters some biomes in a neat and vanilla way!
minecraft_version_range=[26.2, 26.3)
neo_form_version=26.2-1

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_version=0.152.2+26.2
fabric_loader_version=0.19.3
cloth_fabric_version=26.2.155
modmenu_version=20.0.0-beta.3

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=26.2.0.6-beta
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
